version: 2.1

jobs:
  build-and-generate-artifacts:
    docker:
      - image: lokedhs/sbcl-quicklisp
    steps:
      - checkout
      - run:
          name: Process every L-System inside examples/
          command: ./.circleci/build-and-generate.sh
      - store_artifacts:
          path: results

workflows:
  version: 2
  cl-lsystem:
    jobs:
      - build-and-generate-artifacts
